Update release patch

diff --git a/.github/workflows/release_patch.yml b/.github/workflows/release_patch.yml
--- a/.github/workflows/release_patch.yml
+++ b/.github/workflows/release_patch.yml
@@ -7,11 +7,11 @@ on:
       sprintVersion:
         required: true
         type: string
-        description: The full sprint version including patch, e.g. 1.245.2
+        description: The full sprint version including patch number, e.g. 1.245.2
 
 jobs:
   create-release-patch:
-    # Only run this job on release branches
+    # Only allow this workflow to be run on release branches.
     if: startsWith(github.ref_name, 'release/')
 
     runs-on: ubuntu-latest
@@ -20,11 +20,23 @@ jobs:
       - uses: actions/checkout@v3
       - name: Create release patch and tag
         env:
-          SPRINT_VERSION: ${{ inputs.sprintVersion }}
+          SPRINT_VERSION_WITH_PATCH: ${{ inputs.sprintVersion }}
         run: |
-          echo "${{ github.head_ref }}"
-          echo "${{ github.ref }}"
-          echo "${{ github.ref_name }}"
+          [[ ${{ inputs.sprintVersion }} ]] || { echo "Required input sprintVersion not set, exiting."; exit 1; }
           git config user.name github-actions[bot]
           git config user.email github-actions[bot]@users.noreply.github.com
           git config push.autoSetupRemote true
+          sh update_version.sh
+          git add .
+          git commit -m "Release $SPRINT_VERSION_WITH_PATCH"
+          git tag -a v$SPRINT_VERSION_WITH_PATCH -m "Release $SPRINT_VERSION_WITH_PATCH"
+          git push --follow-tags
+
+      # Update the Go modules index so that "go get github.com/Kwintenvdb/go-test-repo"
+      # will resolve to the latest tag.
+      # Users may install a specific version, e.g. "go get github.com/Kwintenvdb/go-test-repo@v1.245.1"
+      - uses: actions/setup-go@v3
+      - name: Update Go modules index
+        env:
+          SPRINT_VERSION_WITH_PATCH: ${{ inputs.sprintVersion }}
+        run: GOPROXY=proxy.golang.org go list -m github.com/Kwintenvdb/go-test-repo@v$SPRINT_VERSION_WITH_PATCH
